name: flutter_esp_android_communication
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.3.0
  string_similarity: ^2.1.1
  usb_serial: ^0.5.2
  provider:
  flutter_map:
  latlong2:
  flutter_map_tile_caching: ^10.0.0
  geolocator:
  flutter_compass:
  flutter_map_location_marker:
  speech_to_text:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
